site_name: UNOPS Exam Software Documentation
site_url: https://EAsrat1.github.io/UNOPS-Exam-Software/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
     # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - Eth Tele Server: eth-tele-server-configuration.md
  - Module: module-codes.md
  - Installation-and-setup: 
    - Environment-Configuration: Installation-and-setup/Environment-Configuration.md
    - Prerequisites: Installation-and-setup/Prerequisites.md
    - Setup-Guide: Installation-and-setup/Setup-Guide.md
site_url: https://easrat1.github.io/UNOPS-Exam-Software/

  




